### ISSUE TITLE
Реализация универсальности блока.

### ISSUE THREAD

**Issue by nn-0** [radon-lab/ArDos_with_RADON#1]
Привет!
У тебя очень крутой проект! Спасибо за проделанную работу!

Но у меня возникла одна интересная идея, заключается она в том, чтобы особо не меняя конструктив какого-либо отдельно взятого промышленно произведенного дозиметра, добавить туда блок ардуино+дисплей+кнопки.
В итоге, получаем на базе практически любого дозиметра - отличный девайс.

Вот к примеру, есть у меня сейчас ДРГБ-01, что мне с него нужно снимать и подавать на ардуино, помимо сигнала счёта на pin2?
Ещё есть ДП-5, аналогично.

Вопросы калибровки я пока поднимать не буду)))

И ещё у меня к тебе две просьбы - добавь, пожалуйста, сюда схему с сайта, и укажи лицензию под которой публикуешь сорцы.

**Comment by radon-lab** [comment]
Если на стороне старого дозика останется преобразователь ВВ и генератор импульсов, то просто подавать импульсы на вход прерывания INT0(pin2) и из прошивки выпилить все что связано с ВВ преобразователем, настроить время счета и мертвое время.
Если от дозика останется только сам датчик, то собираете полностью схему дозиметра с сайта и подключаете к ней датчик. После чего нужно будет узнать характеристики датчика(напряжение питания, время счета, мертвое время) и настроть прошивку и ВВ преобразователь под него.

На счет схемы спрошу на форуме, тк она не моя. Файл лицензии добавил, проект полностью открытый.

**Comment by nn-0** [comment]
Доброго времени суток!

Я хочу попробовать собрать дозиметр на основе счётчика бета-1 с твоей прошивкой, а т.к. например, дозиметр МКС-01 на его основе умеет определять альфу, у меня возникли мысли - а возможно ли в прошивку добавить подобный функционал и что для этого потребуется? Я готов сам поэкспериментировать с этим.
Как я понял, здесь достаточно добавить единицы измерения и всё.

**Comment by nn-0** [comment]
в принципе, я уже нашёл ответы на свои вопросы, благодарю за советы.
