### ISSUE TITLE
Архив предупреждений.

### ISSUE THREAD

**Issue by nekode** [radon-lab/ArDos_with_RADON#3]
Есть возможность вести архив warning'ов? Экран предупреждения/ошибки появляется кратковременно и исчезает бесследно, не увидел - не узнал. Присвоить каждой ошибке байтовый код, вести небольшой архив в оперативке (думаю в еепром класть особого смысла нет). Логировать код ошибки, количество ошибок с данным кодом с момента старта прибора, если есть возможность - приблизительно прошедшее с момента последнего детекта данной ошибки время. Ну и при наличии записей в архиве выводить в статус-бар восклицательный знак (зашли в архив - знак исчез, архив проверен). Строчки на 4-5, больше вряд ли понадобится даже при настройке прибора с нуля.

**Comment by radon-lab** [comment]
Да я думал уже запаковывать ошибки в байт, но посчитал это лишним..мол это же дозиметр а не диагностический тул)) Можно будет в будущем добавить все же.
Сейчас хочу сделать отдельную менюшку для выбора фон/бета/доза/поиск/настройки. Это освободит кучу хоткеев на экранах и как раз можно будет уйти от быстрого меню. Вот только какое лучше сделать? У меня пока 2 варианта - шесть иконок на экране или одна иконка на экране но перемещающаяся.

**Comment by nekode** [comment]
Думаешь графическое меню лучше будет? Сложновато будет подобрать понятные иконки, придётся подписи колхозить. Поиск, бета и настройки не проблема (хотя бета лучше смотреться будет двойной иконкой, знак бета и дельта через "/" ), а остальные как?
Да, действительно, сейчас в хоткеях уже заблудиться можно, хотя туда просятся более простые вещи вроде фонарика.
Может шесть иконок с выбором перемещающейся рамкой, а снизу изменяющееся название выделенного пункта?

**Comment by radon-lab** [comment]
Если честно, пока не думал даже... Думаешь сделать текстовым как и настройки??

**Comment by nekode** [comment]
Можно и графическим. Лупа, гаечный ключ или шестерёнка, бета/дельта, стрелочный индикатор для меню отладки, остальные подберём всем скопом, пока можно пустые квадраты оставить. Всё равно бОльшая часть текста в картинки перекинута. Но подпись-подсказка внизу нужна.

**Comment by radon-lab** [comment]
Подписи не влезут к сожалению..одна иконка будет размером 28х24 и 6 штук как раз полностью занимают весь экран... И вот я сейчас подумал, может и в правду сделать текстовое меню?? Так будет и проще и понятнее пользователю.
Ну вообще нет, на самом деле текста в картинках не очень много... По факту получается так, что они занимают больше места чем обычный текст... Обусловлено это тем, что битмапы мы полностью забиваем в память, а текст обрабатывается всего одним блоком.

**Comment by nekode** [comment]
Пусть пока будет текстовым. Оно действительно понятнее, а захочется красивостей - всегда можно переделать.

**Comment by Gualdimar** [comment]
Если планируется полноценное меню, то было бы удобно розбить меню настроек на категории в несколько уровней(Звук, Тревога, Энергосбережение, Отладка и т.п) и перенести все настройки из дефайнов в меню, дабы не шиться каждый раз.

**Comment by nekode** [comment]
Дефайны хороши тем, что не забирают оперативку. А так мы заберём львиную долю ресурсов контроллера на параметры, из которых пользователем меняться будет лишь несколько, да и то только при первичной наладке прибора. А накосячить с настройками неискушённому юзеру будет в разы проще.
Настроек достаточно два уровня, пользовательские (звук, свет, вибрация, время бета, пороги) и системные (калибровка ацп, накачка, эквивалентное время счёта или множитель CPS/CPM).

А архив всё же нужен, без него сложно ошибки отлавливать. И маячок в таскбаре.

**Comment by Gualdimar** [comment]
Я имею в виду, настройки по типу звук быстрого меню или коррекция мертвого времени. Как такими настройками можно накосячить?

**Comment by nekode** [comment]
Такие имхо в процессе эксплуатации вовсе менять не надо) Посмотрим, что будет в обновлённом меню, может коллегиально что-то предложим добавить/убавить. Но делать большое меню настроек не стоит, затраты и так небольших ресурсов камня того не стоят.

**Comment by radon-lab** [comment]
Про разбитие настроек на подпункты уже думал, в будущем сделаю. Добавить почти все настройки то можно...вопрос нужно ли только? В основном там конфигурации которые то и в жизни трогать не нужно, только раз при прошивке..
