### ISSUE TITLE
Последняя версия все поломала

### ISSUE THREAD

**Issue by Gualdimar** [radon-lab/ArDos_with_RADON#4]
На последней версии после заставки проскакивает экран фон с кучей нулей в строке средн, после чего открывается экран ОТЛАДКА с рандомными числами. Указателя нет, кнопки пикают. Если удерживать ОК, то отобразится экран Сохранить настройки, можно выбрать да/нет, после чего рандомные пиксели/куски на экране.

**Comment by nekode** [comment]
Почти такое же поведение. [3.0.5 08.10.20 76cd349](https://github.com/radon-lab/ArDos_with_RADON/commit/76cd3499da8a1c07f777ec880c1467125b5f6dc9) "Фон" не заметил, сразу после заставки валится в отладку со случайными данными. Через некоторое время самостоятельно предлагает сохранить настройки, накачка цокает с частотой герц 4-5, иногда выкидывает ошибку "нет счёта" (ессесно, высокое то явно не докачивает).
"Сохранить настройки" отрабатывает почти корректно, по "нет" возврат в "отладку", по "да" - "настройки сохранены" и возврат в отладку.

Попытался запустить со сбросом настроек - вообще нет инициализации дисплея, только подсветка. Кнопки озвучиваются, накачка цокает так же редко. Так и не понял, добил сбросом или предыдущим сохранением некорректных настроек.

UPD: Инициализация есть, контраст улетел в очень малое значение, под углом случайно заметил. Симптомы те же, сброс ничего не дал.
UPD2: Было бы неплохо при ресете удержанием при запуске ВСЕ настройки сбрасывать к дефайнам. 400 раз нажать тактовую кнопку для возврата параметра к требуемому после глюка то ещё удовольствие. И это только одного))

**Comment by radon-lab** [comment]
Исправил, забыл проставить нумерацию массива...
Можно сбрасывать все, просто кто-то говорил что это не нужно вот и не стал делать...

**Comment by nekode** [comment]
Можно к частичному сбросу по "Ок" добавить полный по двум стрелкам. Случайно вряд ли зажмёшь, а при поиске багов может пригодиться.
